language: go

go:
  - 1.4
  - tip


# we're in $HOME/gopath/src/github.com/tp/ziputil
install:
  - cd ../../../
  - pwd
  - mkdir timm.io
  - mv github.com/tp/ziputil timm.io/
  - cd timm.io/ziputil
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/lint/golint

script:
  - go vet ./...
  - golint ./...
  - go test -v ./...